# Generated by Django 6.0.5 on 2026-05-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
    ]
